title = "MoonOld Blog"
baseURL = "http://localhost/"
# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
enableGitInfo = true


# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

[params]
  # FixIt 主题版本
  version = "0.2.X"
  description = "MoonOld古月 Blog"
    externalIcon = true
[params.header]
        desktopMode = "sticky"
    [params.header.title]
        name = "MoonOld Blog"
        logo = "/favicon-32x32.png"
[params.social]
    GitHub = "MoonOld"
    Email = "MoonOld.h@gmail.com"
[params.footer]
    enable = true
    hugo = true
    copyright = true
    author = true
    since = 2023
    wordCount = true
    visitor = true
    [params.footer.order]
        powered = 1
        statistics = 2
        visitor = 3

[params.section]
    paginate = 10
    dateFormate = "2000-02-02"
    [params.section.recentlyUpdated]
        enable = true
        days = 30
        maxCount = 10
[params.home]
    # FixIt 0.2.0 | 新增 RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      #gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = "/avatar.png"
      # FixIt 0.2.17 | 新增 头像菜单链接的 identifier
      #avatarMenu = ""
      # FixIt 0.2.7 | 更改 主页显示的网站标题（支持 HTML 格式）
      #title = ""
      # 主页显示的网站副标题
      subtitle = "想给狂放的想法安个家"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # FixIt 0.2.0 | 新增 免责声明（支持 HTML 格式）
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6
[params.page]
    authorAvatar = true
    readingTime = true
    endFlag=""
    autoBookmark = true
    #author = "MoonOld"
    [params.page.toc]
        enable = true
        auto = true
        position = "right"
    [params.page.code]
        copy = true
        maxShownLines = 10
    [params.page.comment]
      enable = true
      [params.page.comment.giscus]
        enable = true
        repo = "MoonOld/Moonold.github.io"
        repoId = "R_kgDOJGe7ZQ"
        category = "Announcements"
        categoryId = "DIC_kwDOJGe7Zc4CVm_a"
        mapping = "pathname"
        strict = "0" # FixIt 0.2.18 | 新增
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "top" # ["top", "bottom"]
        lightTheme = "light"
        darkTheme = "dark"
        lazyLoad = true
    [params.page.share]
        Myspace = false
        twitter = false
        facebook = true
        weibo = false
        zhihu = true
        Linkedin = true

[params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1
[params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "MoonOld Blog"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
    # FixIt 0.2.12 | CHANGED Android browser theme color
    [params.app.themeColor]
     # light = "#f8f8f8"
     # dark = "#252627"
[params.search]
    enable = true
    # type of search engine ["lunr", "algolia", "fuse"]
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # FixIt 0.2.1 | NEW max number of results length
    maxResultLength = 10
    # FixIt 0.2.3 | NEW snippet length of the result
    snippetLength = 30
    # FixIt 0.2.1 | NEW HTML tag name of the highlight part in results
    highlightTag = "em"
    # FixIt 0.2.4 | NEW whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      # FixIt 0.2.17 | NEW https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false



[params.githubCorner]
    enable = true
    permalink = "https://github.com/hugo-fixit/FixIt"
    title = "在 GitHub 上查看源代码"
    position = "right" # ["left", "right"]

 [params.backToTop]
    enable = false
    # 在 b2t 按钮中显示滚动百分比
    scrollpercent = false

[params.readingProgress]
    enable = true
    # 可用值：["left", "right"]
    start = "left"
    # 可用值：["top", "bottom"]
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"

# Hugo 解析文档的配置

[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    ################## 必要的配置 ##################
    # https://github.com/hugo-fixit/FixIt/issues/43
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    ################## 必要的配置 ##################
    guessSyntax = true
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[author]
  name = "MoonOld"
  email = "MoonOld.h@gmail.com"
  #link = ""
  avatar = "/avatar.jpg"

[frontmatter]
  date = ["date", ":filename", "lastmod", ":git"]
  lastmod = [":git", "lastmod", ":fileModTime", ":default"]



[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 1
    [[menu.main]]
        identifier = "Lab"
        name ="Lab"
        url = "/categories/lab"
        parent = "categories"
        weight = 1
        [[menu.main]]
        identifier = "music"
        name ="音乐"
        url = "/categories/音乐" 
        parent = "categories"
        [[menu.main]]
        identifier = "env"
        name ="环境搭建"
        url = "/categories/环境搭建" 
        parent = "categories"

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
    [[menu.main]]
        identifier = "about"
        name = "关于 MoonOld"
        url = "/about"
        weight = 4
    [[menu.main]]
    identifier = "friends"
    name = "友链"
    url = "/friends/"
    title = "友情链接"
    weight = 21
    parent = "about"
        [menu.main.params]
        icon = "fa-solid fa-users"


[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]